Repulsion Stage
Spectator-matter-group-INR-RAS/AAMCC pull request #33
Opened 2024-12-26 13:29 UTC by vskates

2024-12-29 09:11 UTC, alexsvetlichnyy commented
In runs with Pb+Pb@sqrt S_nn 5020 GeV (ALICE energies) once in a 1300 events there is an errror:

/FermiBreakUp/G4FermiPhaseSpaceDecay.cc, line 71: 
===> G4FermiPhaseSpaceDecay::KopylovNBodyDecay: Error sampling fragments momenta

Variable PFragMagCM = -1.0

2024-12-29 09:40 UTC, alexsvetlichnyy commented
[Uploading histoscoulomb.pdf…](QA pdf)

1) No heavy fragments
2) A few protons with eta ~ 0

2024-12-29 09:42 UTC, alexsvetlichnyy commented
After QA:

No heavy fragments
A few protons with eta ~0.
Unphysical light fragments with Z and N not close to each other

2024-12-29 13:17 UTC, apBUSampK requested changes
Checked .cpp files

2024-12-29 13:17 UTC, apBUSampK commented on include/GMSTClustering.hh
> +using namespace std;
"using namespace" shouldn't be used in a header

old code

2024-12-29 13:17 UTC, apBUSampK commented on include/GMSTClustering.hh
> +    list<G4int>* adj;
Should be either array<list<G4int>> or vector<list<G4int>>

old code

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +const double fm = 1e-15;
All these constants should be made constexpr

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +  double minX = (*nucleons)[0].GetX(), maxX = minX;
kinda works, but NucleonVector inhertis std::vector<Nucleon> and therefore supports std::min_element (see [cppreference](https://en.cppreference.com/w/cpp/algorithm/min_element))

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +  double minX = (*nucleons)[0].GetX(), maxX = minX;
will probably look tidier, but doesn't really matter

2024-12-29 13:17 UTC, apBUSampK commented on include/Repulsion.hh
> + public:
probably should be private

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +const double fm = 1e-15;
And moved to header

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +    G4LorentzVector finalMomentum(std::sqrt(newMomentum.mag() * newMomentum.mag() + std::pow(frag_masses[i] * speed_light, 2)), newMomentum);
(mc^2)^2, not (mc)^2

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +    frag->SetMomentum(MeVc * frag->GetMomentum());
I've traced that you call this function only once, but side effects like these are nasty. Please, make momentum scaling a separate function, or at least rename this one to make it apparent.

2024-12-29 13:17 UTC, apBUSampK commented on src/Repulsion.cc
> +void LazyGetForces(const aamcc::NucleonVector* nucleons, const std::vector<int>& maps, std::vector<Vector3d>& fs) {
unused function?

2024-12-29 13:30 UTC, apBUSampK requested changes
shared_ptr usage comment

2024-12-29 13:30 UTC, apBUSampK commented on include/Repulsion.hh
> +  std::vector<std::shared_ptr<BHNode>> children; // child nodes
So after looking through your code, I can't see any valid reasons to use shared_ptr instead of unique_ptr. IIRC, mandatory copy ellision is enforced since C++17, AAMCC is C++11 and therefore `return std::move(unique_ptr_local_instance);` has to be used.

2024-12-29 13:32 UTC, apBUSampK commented
Also, please, don't delete and then upload files, do normal commits with normal deltas in the future (:

2025-01-03 16:50 UTC, alexsvetlichnyy commented
Lot of garbage files from vscode

2025-01-03 17:54 UTC, alexsvetlichnyy commented
[histoscoulomb.pdf](https://github.com/user-attachments/files/18302320/histoscoulomb.pdf)

Physics is ok

2025-01-05 18:47 UTC, apBUSampK commented on src/Repulsion.cc
> +std::unique_ptr<BHNode> BHTree::InsertNucleon(std::unique_ptr<BHNode> node, const G4ThreeVector& cords, int pIndex) {
Change of ownership is unnecessary here, change signature to `void foo(const unique_ptr&, ...)`

2025-01-05 20:05 UTC, apBUSampK approved these changes

2025-01-05 22:23 UTC, merged